apiVersion: v2      # The Kubernetes API version
name: spring-boot-helm-chart
description: A Helm chart for Kubernetes to deploy a Spring Boot application
type: application
version: 1.0.4        # The version of the Helm chart
appVersion: "1.0.3"  # The version of the application being deployed
